vbox-manage:
general:
  name: "AnsibleTest2"
  iso-file-path: D:/piotr/2021_02_13-Linux-Image/lubuntu-18.04.5-desktop-amd64.iso
create:
  predefined:
    vms-home: D:\piotr\2021-02_13-VirtualBox\VirtualMachines
    nat-rule: "guestssh,tcp,127.0.0.2,22,10.0.2.15,22"
    shared-folder:
      name: "MySharedFolderTest"
      host-path: "D:/piotr/2021-02_13-VirtualBox/shared_place"
      auto-mount-point: "/mnt/mysharedfolder"
install:
  predefined:
    full-user-name: "test"
    credentials:
      user: "test"
      password: "test123"
    post-install-command: ""